"""multi-agent-per-clinic: drop unique(agent_configs.tenant_id), add tenants.max_agents, guard duplicate clinic names

Revision ID: 93255d8d413e
Revises: 43b80e6d3738
Create Date: 2026-07-07 12:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93255d8d413e'
down_revision: Union[str, None] = '43b80e6d3738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    dialect = bind.dialect.name

    if dialect == 'postgresql':
        # ── 1. Drop whatever unique constraint enforces one-agent-per-tenant ──
        # Name isn't hardcoded — it was auto-generated by SQLAlchemy/Postgres
        # when the column was originally created with unique=True.
        rows = bind.execute(sa.text("""
            SELECT tc.constraint_name
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu
              ON tc.constraint_name = kcu.constraint_name
             AND tc.table_schema = kcu.table_schema
            WHERE tc.table_name = 'agent_configs'
              AND tc.constraint_type = 'UNIQUE'
              AND kcu.column_name = 'tenant_id'
        """)).fetchall()
        for row in rows:
            op.execute(f'ALTER TABLE agent_configs DROP CONSTRAINT "{row[0]}"')

        # Keep a plain (non-unique) index for FK lookups.
        op.execute("CREATE INDEX IF NOT EXISTS ix_agent_configs_tenant_id ON agent_configs (tenant_id)")

        # ── 2. Future hook for plan-based agent limits — nullable, unenforced ──
        op.execute("ALTER TABLE tenants ADD COLUMN IF NOT EXISTS max_agents INTEGER")

        # ── 3. Prevent two clinics with the same name from being created
        # concurrently (case-insensitive). Requires no pre-existing duplicates.
        op.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS ux_tenants_clinic_name_lower "
            "ON tenants (lower(clinic_name))"
        )
    else:
        # SQLite (local dev only). Inline UNIQUE column constraints can't be
        # dropped without a full table rebuild; local dev data is disposable,
        # so this is best-effort and non-fatal if it can't apply cleanly.
        import contextlib
        with contextlib.suppress(Exception):
            op.execute("ALTER TABLE tenants ADD COLUMN max_agents INTEGER")
        with contextlib.suppress(Exception):
            op.execute(
                "CREATE UNIQUE INDEX IF NOT EXISTS ux_tenants_clinic_name_lower "
                "ON tenants (clinic_name COLLATE NOCASE)"
            )


def downgrade() -> None:
    bind = op.get_bind()
    dialect = bind.dialect.name
    if dialect == 'postgresql':
        op.execute("DROP INDEX IF EXISTS ux_tenants_clinic_name_lower")
        op.execute("ALTER TABLE tenants DROP COLUMN IF EXISTS max_agents")
        op.execute("DROP INDEX IF EXISTS ix_agent_configs_tenant_id")
        op.execute("ALTER TABLE agent_configs ADD CONSTRAINT agent_configs_tenant_id_key UNIQUE (tenant_id)")
    else:
        import contextlib
        with contextlib.suppress(Exception):
            op.execute("DROP INDEX IF EXISTS ux_tenants_clinic_name_lower")
        with contextlib.suppress(Exception):
            with op.batch_alter_table('tenants', schema=None) as batch_op:
                batch_op.drop_column('max_agents')
